### ISSUE TITLE
Support Confluence DataCenter/Server

### ISSUE THREAD

**Issue by skleinei** [skleinei/alfred-confluence#17]
I'm still on the fence whether Confluence Quicksearch for Alfred should DataCenter (and Server). Please comment here, if you need it.

**Comment by dmittman** [comment]
Alfred could be the centerpiece of a "bring federated search to the desktop" design principle. Rather than build an intranet crawler, bespoke index, and search portal, rely on Alfred to search multiple information repositories and display the results a la Spotlight on the user's desktop. Confluence Server is one such information repository. With Alfred, it should be possible to search Confluence, Jira, DocuShare, Alfresco, GitHub Enterprise, and many other "API-enabled" repositories with command. That’s my use case for Alfred's Confluence Server connector.

**Comment by skleinei** [comment]
It looks like the Confluence search API on Cloud and DataCenter is fairly similar, so that the implementation is/was very straight forward. Bottom-line: Server/Datacenter support is working. Feel free to test it out:
[confluence-quicksearch.alfredworkflow.zip](https://github.com/skleinei/alfred-confluence/files/9501233/confluence-quicksearch.alfredworkflow.zip). (You'll have to rename the attached file from `confluence-quicksearch.alfredworkflow.zip` to `confluence-quicksearch.alfredworkflow`, as Github would not allow me to upload a file of type `alfredworkflow`. 🤷‍♂️ )

This is just a beta, because I have to rename the labels in the config UI and docs.

Downside: you have to enter your password in the token field, which is stored visibly and unencrypted. It looks like Alfred team is working on [support for proper password fields](https://www.alfredforum.com/topic/18719-alfred-5-add-user-configuration-password-field).

Let me know if that works.

**Comment by skleinei** [comment]
Fixed in https://github.com/skleinei/alfred-confluence/releases/tag/2.0.1
